# Generated by Django 2.2.6 on 2020-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
